name: Backend Tests

on:
  push:
    branches: [backend-dev]
  pull_request:
    branches: [backend-dev]

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Configure Test Environment
        working-directory: ./backend
        env: ${{ secrets }}
        run: |
          envsubst < src/test/resources/.env.template > src/test/resources/.env

      - name: Make Maven wrapper executable
        working-directory: ./backend
        run: chmod +x mvnw

      - name: Test Backend
        working-directory: ./backend
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./mvnw clean verify

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./backend/target/site/jacoco/jacoco.xml