name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Production
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04
    environment: production
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Backend Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/qlish-backend:${{ github.sha }}

      - name: Pull Frontend Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/qlish-frontend:${{ github.sha }}

#      - name: Deploy to Production
#        uses: appleboy/ssh-action@v1
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_KEY }}
#          script: |
#            docker compose pull
#            docker compose up -d --force-recreate
#            docker image prune -af