name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    needs:
      - backend-tests
      - frontend-tests
    env:
      APP_NAME: ${{ secrets.APP_NAME }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CLIENT_REDIRECT_URI: ${{ secrets.GOOGLE_CLIENT_REDIRECT_URI }}
      GOOGLE_CLIENT_AUTHORIZATION_URI: ${{ secrets.GOOGLE_CLIENT_AUTHORIZATION_URI }}
      GOOGLE_CLIENT_TOKEN_URI: ${{ secrets.GOOGLE_CLIENT_TOKEN_URI }}
      USER_INFO_URI: ${{ secrets.USER_INFO_URI }}
      MONGO_URL: ${{ secrets.MONGO_URL }}
      DB_NAME: ${{ secrets.DB_NAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
      JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
      ACCESS_TOKEN_EXPIRATION: ${{ secrets.ACCESS_TOKEN_EXPIRATION }}
      REFRESH_TOKEN_EXPIRATION: ${{ secrets.REFRESH_TOKEN_EXPIRATION }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create backend env file
        working-directory: ./backend
        run: |
          echo "APP_NAME=${APP_NAME}" >> .env
          echo "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" >> .env
          echo "GOOGLE_CLIENT_REDIRECT_URI=${GOOGLE_CLIENT_REDIRECT_URI}" >> .env
          echo "GOOGLE_CLIENT_AUTHORIZATION_URI=${GOOGLE_CLIENT_AUTHORIZATION_URI}" >> .env
          echo "GOOGLE_CLIENT_TOKEN_URI=${GOOGLE_CLIENT_TOKEN_URI}" >> .env
          echo "USER_INFO_URI=${USER_INFO_URI}" >> .env
          echo "MONGO_URL=${MONGO_URL}" >> .env
          echo "DB_NAME=${DB_NAME}" >> .env
          echo "MONGO_PASSWORD=${MONGO_PASSWORD}" >> .env
          echo "MONGO_USERNAME=${MONGO_USERNAME}" >> .env
          echo "REDIS_HOST=${REDIS_HOST}" >> .env
          echo "REDIS_PORT=${REDIS_PORT}" >> .env
          echo "REDIS_PASSWORD=${REDIS_PASSWORD}" >> .env
          echo "JWT_SECRET=${JWT_SECRET}" >> .env
          echo "JWT_ISSUER=${JWT_ISSUER}" >> .env
          echo "JWT_AUDIENCE=${JWT_AUDIENCE}" >> .env
          echo "ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}" >> .env
          echo "REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}" >> .env

      - name: Create frontend env file
        working-directory: ./frontend
        run: |
          echo "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}" >> .env

      - name: Build Backend Docker Image
        working-directory: ./backend
        run: docker build -t qlish-backend:${{ github.sha }} .

      - name: Build Frontend Docker Image
        working-directory: ./frontend
        run: docker build -t qlish-frontend:${{ github.sha }} .

      - name: Push Backend Image to Docker Hub
        working-directory: ./backend
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag qlish-backend:${{ github.sha }} kolade20/qlish-backend:latest
          docker push kolade20/qlish-backend:latest

      - name: Push Frontend Image to Docker Hub
        working-directory: ./frontend
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag qlish-frontend:${{ github.sha }} kolade20/qlish-frontend:latest
          docker push kolade20/qlish-frontend:latest

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            docker pull kolade20/qlish-backend:latest
            docker pull kolade20/qlish-frontend:latest
            docker-compose down
            docker-compose up -d
          EOF
