name: Build Docker Images

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_run:
    workflows:
      - Backend Tests
      - Frontend Tests
    types:
      - completed

jobs:
  build-docker-images:
    name: Docker Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure App Environment
        env: ${{ secrets }}
        run: |
          envsubst < ./backend/.env.template > ./backend/.env
          envsubst < ./frontend/.env.template > ./frontend/.env

      - name: Build Backend Docker Image
        working-directory: ./backend
        run: docker build -t backend-app:${{ github.sha }} .

      - name: Build Frontend Docker Image
        working-directory: ./frontend
        run: docker build -t frontend-app:${{ github.sha }} .